

name: Pushing sourcemaps to sentry

on:
  push:
      branches: [ master ]

jobs:
  deploy-deva:
    name: Deploy Deva
    runs-on: ubuntu-latest

    steps:
#      - name: Test and Build
#        run: |
#          npm i
#          npm run build
      - name: Sentry release
        uses: getsentry/action-release@v1.2.1
        env:
          SENTRY_ORG: yuriyp
          SENTRY_AUTH_TOKEN: 2b0d35b0a8634ebf9678003eaf9e8c8c7a477a5a96864240a14df4bee0624154
          SENTRY_PROJECT: yuriy-yest
        with:
          url_prefix: '~/static/js'
          sourcemaps: './build/static/js/'